
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVANCAR BAIXAR_CANETA FIM GIRAR_DIREITA GIRAR_ESQUERDA INICIO LEVANTAR_CANETA NUMERO VOLTARprograma : INICIO comandos FIMcomandos : comandos comando\n                | comandocomando : LEVANTAR_CANETA\n               | BAIXAR_CANETAcomando : AVANCAR NUMERO\n               | VOLTAR NUMERO\n               | GIRAR_DIREITA NUMERO\n               | GIRAR_ESQUERDA NUMERO'
    
_lr_action_items = {'INICIO':([0,],[2,]),'$end':([1,11,],[0,-1,]),'LEVANTAR_CANETA':([2,3,4,5,6,12,13,14,15,16,],[5,5,-3,-4,-5,-2,-6,-7,-8,-9,]),'BAIXAR_CANETA':([2,3,4,5,6,12,13,14,15,16,],[6,6,-3,-4,-5,-2,-6,-7,-8,-9,]),'AVANCAR':([2,3,4,5,6,12,13,14,15,16,],[7,7,-3,-4,-5,-2,-6,-7,-8,-9,]),'VOLTAR':([2,3,4,5,6,12,13,14,15,16,],[8,8,-3,-4,-5,-2,-6,-7,-8,-9,]),'GIRAR_DIREITA':([2,3,4,5,6,12,13,14,15,16,],[9,9,-3,-4,-5,-2,-6,-7,-8,-9,]),'GIRAR_ESQUERDA':([2,3,4,5,6,12,13,14,15,16,],[10,10,-3,-4,-5,-2,-6,-7,-8,-9,]),'FIM':([3,4,5,6,12,13,14,15,16,],[11,-3,-4,-5,-2,-6,-7,-8,-9,]),'NUMERO':([7,8,9,10,],[13,14,15,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'comandos':([2,],[3,]),'comando':([2,3,],[4,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> INICIO comandos FIM','programa',3,'p_programa','parser.py',5),
  ('comandos -> comandos comando','comandos',2,'p_comandos','parser.py',9),
  ('comandos -> comando','comandos',1,'p_comandos','parser.py',10),
  ('comando -> LEVANTAR_CANETA','comando',1,'p_comando_simples','parser.py',17),
  ('comando -> BAIXAR_CANETA','comando',1,'p_comando_simples','parser.py',18),
  ('comando -> AVANCAR NUMERO','comando',2,'p_comando_param','parser.py',22),
  ('comando -> VOLTAR NUMERO','comando',2,'p_comando_param','parser.py',23),
  ('comando -> GIRAR_DIREITA NUMERO','comando',2,'p_comando_param','parser.py',24),
  ('comando -> GIRAR_ESQUERDA NUMERO','comando',2,'p_comando_param','parser.py',25),
]
